name: Build and Compile Python Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-windows_x64:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Setup Environment
        run: |
          pip install briefcase==0.3.20 nuitka==1.0.6 ordered-set==4.1.0

      - name: compile app to pyd
        run: |
          cd helloworld
          python -m nuitka --module src/helloworld/app --include-package=app --show-progress  --output-dir=dist --remove-output
          copy .\dist\*.pyd src\helloworld
          Remove-Item -Path 'src\helloworld\app' -Recurse -Force

      - name: Build App
        run: |
          cd helloworld
          briefcase create
          briefcase build
          briefcase package -p zip

      - name: Upload Windows Executable
        uses: actions/upload-artifact@v4
        with:
          name: windows-executable
          path: helloworld/dist/*.zip

  